import asyncio
from loguru import logger

from instacrud.model.system_model import AiModel, AiServiceProvider, Tier
from instacrud.database import init_system_db

# -------------------------------------------------------------------
# Tiers Data
# -------------------------------------------------------------------
TIERS = [
    {"tier": 1, "name": "Free", "code": "free", "usage": 0.01, "active": True},
    {"tier": 5, "name": "Pro", "code": "pro", "usage": 0.4, "active": True},
    {"tier": 10, "name": "Premium", "code": "premium", "usage": 1, "active": True},
    {"tier": 15, "name": "Platinum", "code": "platinum", "usage": 2.5, "active": True},
]

# -------------------------------------------------------------------
# AI Models Data
# -------------------------------------------------------------------
# Each model entry is a dict with the following fields:
#
#   service           – AiServiceProvider enum (OPEN_AI, CLAUDE, DEEP_INFRA, OLLAMA)
#   name              – Human-readable display name shown in the UI
#   model_identifier  – Exact API model ID sent to the provider
#   temperature       – Sampling temperature (omit for models that don't support it,
#                         e.g. the GPT-5/GPT-6 series and always-thinking Claude models)
#   max_tokens        – Maximum output token limit for this model
#   credits           – Internal credit cost charged per request (billing unit = USD × 10 000):
#                         • LLMs:      cost of a typical chat (4 000 input + 1 000 output tokens) × 10 000
#                                      = round(40 × input_cost + 10 × output_cost)
#                         • Images:    cost of one generated image × 10 000  (= input_tokens_cost × 10 000)
#                         • Embeddings: flat minimum of 1 (actual token cost is negligible)
#   input_tokens_cost – Provider's cost in USD per 1,000,000 input tokens
#                         (for image models: USD per generated image)
#   output_tokens_cost– Provider's cost in USD per 1,000,000 output tokens
#                         (0.0 for embeddings; for image models: USD for the top quality tier, informational)
#   completion        – True if the model supports text/chat completion
#   embedding         – True if the model produces vector embeddings
#   image_completion  – True if the model can accept image input (vision)
#   image_generation  – True if the model generates images as output
#   reasoning         – True if the model has built-in chain-of-thought / reasoning mode
#   enabled           – Whether the model is active and selectable by users
#   rank              – Sort order within its service group (lower = shown first)
#   tier              – Minimum subscription tier required (matches Tier.tier values: 1=Free, 5=Pro, …)
#   icon              – URL or path to the provider logo displayed in the UI
#   params            – (optional) Extra provider-specific settings, e.g. image resolution options
#
# Prices validated against provider pricing pages on 2026-10-01. Credits recomputed from
# those prices with the formula above.
# -------------------------------------------------------------------
ICON_OPENAI = "/icons/openai.svg"
ICON_ANTHROPIC = "https://cdn.simpleicons.org/anthropic/000000"
ICON_DEEPINFRA = "https://deepinfra.com/favicon.ico"
ICON_OLLAMA = "https://cdn.simpleicons.org/ollama/000000"

AI_MODELS = [
    # ===================== OPENAI – COMPLETION =====================
    # Note: GPT-5 and GPT-6 series models do NOT support the temperature parameter.
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-6 Astra",
        "model_identifier": "gpt-6-astra",
        "max_tokens": 128000,
        "credits": 900,
        "input_tokens_cost": 10.0,
        "output_tokens_cost": 50.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 8,
        "tier": 10,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-6.1 Sol",
        "model_identifier": "gpt-6.1-sol",
        "max_tokens": 128000,
        "credits": 180,
        "input_tokens_cost": 2.0,
        "output_tokens_cost": 10.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 1,  # default chat model (lowest rank = picked as default)
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-5.4 Mini",
        "model_identifier": "gpt-5.4-mini",
        "max_tokens": 128000,
        "credits": 75,
        "input_tokens_cost": 0.75,
        "output_tokens_cost": 4.50,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 35,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-5.4 Nano",
        "model_identifier": "gpt-5.4-nano",
        "max_tokens": 128000,
        "credits": 20,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 1.25,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 40,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-6 Luna",
        "model_identifier": "gpt-6-luna",
        "max_tokens": 128000,
        "credits": 9,
        "input_tokens_cost": 0.10,
        "output_tokens_cost": 0.50,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 45,
        "tier": 5,
        "icon": ICON_OPENAI,
    },

    # ===================== OPENAI – EMBEDDINGS =====================
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "Embedding 3 Small",
        "model_identifier": "text-embedding-3-small",
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.02,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 15,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "Embedding 3 Large",
        "model_identifier": "text-embedding-3-large",
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.13,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 25,
        "tier": 5,
        "icon": ICON_OPENAI,
    },

    # ===================== OPENAI – IMAGE =====================
    # These GPT-Image-2.x models bill per token at identical rates; OpenAI publishes no flat
    # per-image price. Credits use an estimated per-image cost (medium ~$0.012, high ~$0.047 at
    # 1024x1024). Sunburst defaults to the high tier (most capable); Flare/Image-2 to medium.
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT Image 2.5 Sunburst",
        "model_identifier": "gpt-image-2.5-sunburst",
        "credits": 470,
        "input_tokens_cost": 0.047,
        "output_tokens_cost": 0.047,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 18,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1024x1536", "1536x1024"],
            "quality": ["low", "medium", "high"]
        },
        "tier": 10,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT Image 2.5 Flare",
        "model_identifier": "gpt-image-2.5-flare",
        "credits": 120,
        "input_tokens_cost": 0.012,
        "output_tokens_cost": 0.047,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 1,  # default image model (lowest rank = picked as default)
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1024x1536", "1536x1024"],
            "quality": ["low", "medium", "high"]
        },
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT Image 2",
        "model_identifier": "gpt-image-2",
        "credits": 120,
        "input_tokens_cost": 0.012,
        "output_tokens_cost": 0.047,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 22,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1024x1536", "1536x1024"],
            "quality": ["low", "medium", "high"]
        },
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT Image 1.5",
        "model_identifier": "gpt-image-1.5",
        "credits": 340,
        "input_tokens_cost": 0.034,
        "output_tokens_cost": 0.133,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 90,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1024x1536", "1536x1024"],
            "quality": ["low", "medium", "high"]
        },
        "tier": 5,
        "icon": ICON_OPENAI,
    },

    # ===================== CLAUDE – COMPLETION =====================
    # Fable 5.1 keeps thinking always on, so it omits the temperature parameter.
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude Fable 5.1",
        "model_identifier": "claude-fable-5-1",
        "max_tokens": 128000,
        "credits": 900,
        "input_tokens_cost": 10.0,
        "output_tokens_cost": 50.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 8,
        "tier": 10,
        "icon": ICON_ANTHROPIC,
    },
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 5.5 Sonnet",
        "model_identifier": "claude-sonnet-5-5",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 180,
        "input_tokens_cost": 2.0,
        "output_tokens_cost": 10.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 12,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 5.5 Opus",
        "model_identifier": "claude-opus-5-5",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 360,
        "input_tokens_cost": 4.0,
        "output_tokens_cost": 20.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 18,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 4.8 Opus",
        "model_identifier": "claude-opus-4-8",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 450,
        "input_tokens_cost": 5.0,
        "output_tokens_cost": 25.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 20,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 4.5 Haiku",
        "model_identifier": "claude-haiku-4-5",
        "temperature": 0.7,
        "max_tokens": 64000,
        "credits": 90,
        "input_tokens_cost": 1.0,
        "output_tokens_cost": 5.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 25,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },

    # ===================== DEEPINFRA – COMPLETION =====================
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 3.1 8B Turbo",
        "model_identifier": "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 1,
        "input_tokens_cost": 0.02,
        "output_tokens_cost": 0.04,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 50,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 3.3 70B Turbo",
        "model_identifier": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 7,
        "input_tokens_cost": 0.10,
        "output_tokens_cost": 0.32,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 4 Scout",
        "model_identifier": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        "temperature": 0.7,
        "max_tokens": 320000,
        "credits": 7,
        "input_tokens_cost": 0.10,
        "output_tokens_cost": 0.30,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 70,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "DeepSeek V4 Pro",
        "model_identifier": "deepseek-ai/DeepSeek-V4-Pro",
        "temperature": 0.7,
        "max_tokens": 163840,
        "credits": 78,
        "input_tokens_cost": 1.30,
        "output_tokens_cost": 2.60,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 5,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "DeepSeek V4.1 Flash",
        "model_identifier": "deepseek-ai/DeepSeek-V4.1-Flash",
        "temperature": 0.7,
        "max_tokens": 163840,
        "credits": 10,
        "input_tokens_cost": 0.14,
        "output_tokens_cost": 0.42,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 6,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "DeepSeek R1",
        "model_identifier": "deepseek-ai/DeepSeek-R1-0528",
        "temperature": 0.6,
        "max_tokens": 163840,
        "credits": 42,
        "input_tokens_cost": 0.50,
        "output_tokens_cost": 2.15,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 16,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "GLM-5.3",
        "model_identifier": "zai-org/GLM-5.3",
        "temperature": 0.7,
        "max_tokens": 204800,
        "credits": 48,
        "input_tokens_cost": 0.563,
        "output_tokens_cost": 2.50,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 9,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "GLM-5.3 Flash",
        "model_identifier": "zai-org/GLM-5.3-Flash",
        "temperature": 0.7,
        "max_tokens": 204800,
        "credits": 6,
        "input_tokens_cost": 0.075,
        "output_tokens_cost": 0.25,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 7,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen3.8",
        "model_identifier": "Qwen/Qwen3.8-2.4T-A95B",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 140,
        "input_tokens_cost": 2.00,
        "output_tokens_cost": 6.00,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 8,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen3 Max",
        "model_identifier": "Qwen/Qwen3-Max",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 108,
        "input_tokens_cost": 1.20,
        "output_tokens_cost": 6.00,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 13,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Kimi K3",
        "model_identifier": "moonshotai/Kimi-K3",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 256,
        "input_tokens_cost": 2.85,
        "output_tokens_cost": 14.25,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 14,
        "tier": 10,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "MiniMax M3",
        "model_identifier": "MiniMaxAI/MiniMax-M3",
        "temperature": 0.7,
        "max_tokens": 1000000,
        "credits": 22,
        "input_tokens_cost": 0.28,
        "output_tokens_cost": 1.10,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 15,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },

    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 4 Maverick",
        "model_identifier": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo",
        "temperature": 0.7,
        "max_tokens": 1000000,
        "credits": 25,
        "input_tokens_cost": 0.50,
        "output_tokens_cost": 0.50,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 28,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Hunyuan Hy4",
        "model_identifier": "tencent/Hy4-preview",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 58,
        "input_tokens_cost": 0.834,
        "output_tokens_cost": 2.501,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 10,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Seed 1.8",
        "model_identifier": "ByteDance/Seed-1.8",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 30,
        "input_tokens_cost": 0.25,
        "output_tokens_cost": 2.00,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 17,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Nemotron 3 Ultra 550B",
        "model_identifier": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 42,
        "input_tokens_cost": 0.50,
        "output_tokens_cost": 2.20,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 18,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "MiMo V2.6 Pro",
        "model_identifier": "XiaomiMiMo/MiMo-V2.6-Pro",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 26,
        "input_tokens_cost": 0.43,
        "output_tokens_cost": 0.87,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 19,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Gemma 4 26B A4B",
        "model_identifier": "google/gemma-4-26B-A4B-it",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 6,
        "input_tokens_cost": 0.07,
        "output_tokens_cost": 0.34,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 65,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },

    # ===================== DEEPINFRA – EMBEDDINGS =====================
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "BGE-M3",
        "model_identifier": "BAAI/bge-m3",
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.01,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 20,  # default search embedding (DEFAULT_EMBEDDING_MODEL)
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "EmbeddingGemma 300m",
        "model_identifier": "google/embeddinggemma-300m",
        "max_tokens": 2048,
        "credits": 1,
        "input_tokens_cost": 0.002,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 25,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen3 Embedding 0.6B",
        "model_identifier": "Qwen/Qwen3-Embedding-0.6B",
        "max_tokens": 32768,
        "credits": 1,
        "input_tokens_cost": 0.01,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen3 Embedding 8B",
        "model_identifier": "Qwen/Qwen3-Embedding-8B",
        "max_tokens": 32768,
        "credits": 1,
        "input_tokens_cost": 0.01,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 35,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },

    # ===================== DEEPINFRA – IMAGE =====================
    # DeepInfra bills most of these per megapixel × steps; per-image credit assumes a
    # 1024x1024 output at each model's default step count.
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 2 Max",
        "model_identifier": "black-forest-labs/FLUX-2-max",
        "credits": 700,
        "input_tokens_cost": 0.07,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 20,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 2 Dev",
        "model_identifier": "black-forest-labs/FLUX-2-dev",
        "credits": 100,
        "input_tokens_cost": 0.01,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 25,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 1 Dev",
        "model_identifier": "black-forest-labs/FLUX-1-dev",
        "credits": 90,
        "input_tokens_cost": 0.009,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 1 Schnell",
        "model_identifier": "black-forest-labs/FLUX-1-schnell",
        "credits": 20,
        "input_tokens_cost": 0.002,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 35,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "SDXL Turbo",
        "model_identifier": "stabilityai/sdxl-turbo",
        "credits": 2,
        "input_tokens_cost": 0.0002,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 40,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"]
        },
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Bria 3.2",
        "model_identifier": "Bria/Bria-3.2",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 45,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1280x768", "1344x768", "832x1216", "1152x832", "1216x832", "960x1088"]
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Bria 3.2 Vector",
        "model_identifier": "Bria/Bria-3.2-vector",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 46,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1280x768", "1344x768", "832x1216", "1152x832", "1216x832", "960x1088"]
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Seedream 4",
        "model_identifier": "ByteDance/Seedream-4",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 55,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024","1728x3072","2048x2048","2304x4096","3072x1728","3840x1600","4096x2304","4096x4096"],
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },

    # ===================== OLLAMA – COMPLETION =====================
    # Local models — costs are notional (self-hosted), not provider list prices.
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Mixtral 8x7B",
        "model_identifier": "mixtral:latest",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 27,
        "input_tokens_cost": 0.54,
        "output_tokens_cost": 0.54,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 50,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Mistral 7B",
        "model_identifier": "mistral:latest",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 60,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "DeepSeek R1 Distill 14B",
        "model_identifier": "deepseek-r1:14b",
        "temperature": 0.6,
        "max_tokens": 128000,
        "credits": 15,
        "input_tokens_cost": 0.30,
        "output_tokens_cost": 0.30,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 40,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Llama 3.2 Vision",
        "model_identifier": "llama3.2-vision:11b",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 55,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Qwen 3.5 9B",
        "model_identifier": "qwen3.5:9b",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 65,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Qwen3 VL 8B",
        "model_identifier": "qwen3-vl:8b",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 70,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Gemma 4 12B",
        "model_identifier": "gemma4:12b",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 72,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },

    # ===================== OLLAMA – EMBEDDINGS =====================
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Nomic Embed v1.5",
        "model_identifier": "nomic-embed-text:latest",
        "temperature": 0.0,
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 40,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "BGE-M3",
        "model_identifier": "bge-m3",
        "temperature": 0.0,
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.0,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Qwen3 Embedding 0.6B",
        "model_identifier": "qwen3-embedding:0.6b",
        "temperature": 0.0,
        "max_tokens": 32768,
        "credits": 1,
        "input_tokens_cost": 0.0,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 32,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Qwen3 Embedding 8B",
        "model_identifier": "qwen3-embedding:8b",
        "temperature": 0.0,
        "max_tokens": 32768,
        "credits": 1,
        "input_tokens_cost": 0.0,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 34,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "EmbeddingGemma 300m",
        "model_identifier": "embeddinggemma",
        "temperature": 0.0,
        "max_tokens": 2048,
        "credits": 1,
        "input_tokens_cost": 0.0,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 36,
        "tier": 5,
        "icon": ICON_OLLAMA,
    }
]


async def main():
    # Init system DB
    await init_system_db()

    # Cleanup and insert tiers
    await Tier.delete_all()
    for tier_data in TIERS:
        tier = Tier(**tier_data)
        await tier.insert()
    logger.success(f"Tiers initialized: {len(TIERS)} tiers added.")

    # Cleanup AI models collection
    await AiModel.delete_all()

    # Insert AI models
    for model_data in AI_MODELS:
        ai_model = AiModel(**model_data)
        await ai_model.insert()

    logger.success(f"AI Models initialized: {len(AI_MODELS)} models added.")


if __name__ == "__main__":
    asyncio.run(main())
